alter table if exists projects enable row level security;
alter table if exists specs enable row level security;
alter table if exists tasks enable row level security;
alter table if exists model_usage enable row level security;
alter table if exists agent_runs enable row level security;
alter table if exists tool_runs enable row level security;
alter table if exists workflow_runs enable row level security;
alter table if exists harness_results enable row level security;
alter table if exists artifacts enable row level security;
alter table if exists knowledge_chunks enable row level security;
alter table if exists decisions enable row level security;
alter table if exists model_routes enable row level security;
alter table if exists cost_budgets enable row level security;
alter table if exists service_health enable row level security;
alter table if exists secrets_registry enable row level security;
alter table if exists reusable_patterns enable row level security;

revoke all on projects from anon, authenticated;
revoke all on specs from anon, authenticated;
revoke all on tasks from anon, authenticated;
revoke all on model_usage from anon, authenticated;
revoke all on agent_runs from anon, authenticated;
revoke all on tool_runs from anon, authenticated;
revoke all on workflow_runs from anon, authenticated;
revoke all on harness_results from anon, authenticated;
revoke all on artifacts from anon, authenticated;
revoke all on knowledge_chunks from anon, authenticated;
revoke all on decisions from anon, authenticated;
revoke all on model_routes from anon, authenticated;
revoke all on cost_budgets from anon, authenticated;
revoke all on service_health from anon, authenticated;
revoke all on secrets_registry from anon, authenticated;
revoke all on reusable_patterns from anon, authenticated;
